language: python

python:
  - 3.6

node_js:
  - '8'

env:
  - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/server

addons:
  apt:
    sources:
    - debian-sid

before_install:
  - nvm install-latest-npm

install:
  - pip install -r server/requirements.txt
  - pip install pylint
  # for eslint
  - npm install ms
  - npm install --only=dev

script:
  # Disable duplicate-code since there are some problems related to it. One of
  # the problems described here https://github.com/PyCQA/pylint/issues/2368.
  - find -name "*.py" -not -path "./.git/*" ! -name "setup.py" ! -name "runtests.py" | xargs pylint --disable=R0801
  - python3 -m tornado.testing server/test/runtests.py
  - npm run lint

cache:
  directories:
    - node_modules
